[workspace]

[package]
name = "ecpdksap"
version = "0.2.0"
edition = "2021"
rust-version = "1.82"
build = "build.rs"

[[bin]]
name = "ecpdksap"
path = "src/ecpdksap.rs"

[dependencies]
pallet-revive-uapi  = { version = "0.10", default-features = false }
polkavm-derive      = { version = "0.31.0" }
pvm-contract-macros = { git = "https://github.com/paritytech/cargo-pvm-contract" }
pvm-contract-types  = { git = "https://github.com/paritytech/cargo-pvm-contract", features = ["alloc"] }
ruint               = { version = "1.17", default-features = false, features = ["alloc"] }
picoalloc           = "5"

[features]
abi-gen = []

[build-dependencies]
cargo-pvm-contract-builder = "0.3.0"

[profile.release]
codegen-units    = 1
lto              = true
opt-level        = "z"
panic            = "abort"
strip            = true
overflow-checks  = false