import hre from "hardhat";
import * as fs from "fs";
import * as path from "path";

const DEPLOYMENTS_TS = path.resolve(__dirname, "../../../web/src/config/deployment.ts");
const DEPLOYMENTS_JSON = path.resolve(__dirname, "../../../deployments.json");

const POLKAVM_ARTIFACT = path.resolve(__dirname, "../target/ecpdksap.release.polkavm");

function updateDeployments(address: string) {
	// Write deployments.json at project root
	fs.writeFileSync(DEPLOYMENTS_JSON, JSON.stringify({ contractAddress: address }, null, 2) + "\n");

	// Write TS config for the web app
	const ts = `// Auto-generated by deploy script — do not edit manually
export const contractAddress: string | null = "${address}";
`;
	fs.writeFileSync(DEPLOYMENTS_TS, ts);
}

async function main() {
	if (!fs.existsSync(POLKAVM_ARTIFACT)) {
		throw new Error(
			`${POLKAVM_ARTIFACT} not found.\nRun: cd contracts/stealth && cargo build --release`,
		);
	}

	const polkavmBytes = fs.readFileSync(POLKAVM_ARTIFACT);
	const bytecode = ("0x" + polkavmBytes.toString("hex")) as `0x${string}`;

	console.log(`Deploying ECPDKSAP / Rust (${polkavmBytes.length} bytes)...`);

	const [walletClient] = await hre.viem.getWalletClients();
	const publicClient = await hre.viem.getPublicClient();

	const hash = await walletClient.deployContract({
		abi: [],
		bytecode,
	});

	const receipt = await publicClient.waitForTransactionReceipt({ hash, timeout: 120_000 });

	if (!receipt.contractAddress) {
		throw new Error(`Deploy tx ${hash} did not create a contract`);
	}

	const address = receipt.contractAddress;
	console.log(`ECPDKSAP deployed to: ${address}`);

	updateDeployments(address);
	console.log("Updated deployments.json and web/src/config/deployment.ts");
}

main().catch((error) => {
	console.error(error);
	process.exitCode = 1;
});